export const BUTTON_COLUMN_WIDTH_PERCENT = 22;
export const CHORDS_COLUMN_WIDTH_PERCENT = 100 - BUTTON_COLUMN_WIDTH_PERCENT;
export const COLUMN_GAP_REM = 1.25;
export const CORE_PROGRESSION_ROW_BUTTON_WIDTH_REM = 9;
export const CORE_PROGRESSION_ROW_GAP_REM = 0.5;
